### ISSUE TITLE
Correggere un bug

### ISSUE THREAD

**Issue by GiovanniCardamone** [programmingForFun/workingTogheter#1]
C'e' un bug nel file primofile, vorrei che lo correggessi, in particolare

Stringa numero 3! compare nella riga due, e
Questa e' la seconda stringa, invece e nella riga tre.

vorrei che invertissi l'ordine delle stringhe.

**Comment by ilovelinux** [comment]
Ho risolto il bug riguardante l'inversione delle righe. Commit: 5d59d023031a16f047e0384dbb9cf179e0eb391d
